services:
  rtch-web:
    container_name: rtch-web
    image: nginx:alpine
    ports:
      - "9090:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rtch-app
    networks:
      - rtch-network

  rtch-app:
    container_name: rtch-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - rtch-postgres
    volumes:
      - ./:/var/www
    networks:
      - rtch-network

  rtch-postgres:
    image: postgres
    container_name: rtch-postgres
    restart: always
    expose:
      - 5432
    ports:
      - "2345:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - rtch_postgres_data:/var/lib/postgresql/data
    networks:
      - rtch-network

  rtch-pgadmin:
    image: dpage/pgadmin4
    container_name: rtch-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8000:80"
    networks:
      - rtch-network

  rtch-node:
    image: node:22
    container_name: rtch-node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    tty: true
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install && npm run dev"
    networks:
      - rtch-network

networks:
  rtch-network:
    driver: bridge

volumes:
  rtch_postgres_data:
