services:
  rtch_web:
    container_name: rtch_web
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rtch_app
    networks:
      - rtch-network

  rtch_app:
    container_name: rtch_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - rtch_db
    volumes:
      - ./:/var/www
    networks:
      - rtch-network

  rtch_db:
    image: postgres
    container_name: rtch_db
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - rtch_db:/var/lib/postgresql/data
    networks:
      - rtch-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - rtch-network

  rtch_node:
    image: node:22
    container_name: rtch_node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    tty: true
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install && npm run dev"
    networks:
      - rtch-network

networks:
  rtch-network:
    driver: bridge

volumes:
  rtch_db:
